package api

import "errors"

var (
	ErrInvalidRefreshToken  = errors.New("invalid or expired refresh token")
	ErrSessionReplaced      = errors.New("session replaced by another device")
	ErrRateLimited          = errors.New("rate limited")
	ErrInvalidCode          = errors.New("验证码无效或已过期")
	ErrDuplicateEmail       = errors.New("该邮箱已注册")
	ErrDuplicateUsername    = errors.New("用户名已被使用")
	ErrUserNotFound         = errors.New("用户不存在")
	ErrInvalidPassword      = errors.New("密码错误")
	ErrNicknameTaken        = errors.New("昵称已被使用")
	ErrImageNotFound        = errors.New("图片不存在")
	ErrImageNotOwned        = errors.New("该图片不属于您")
	ErrGameNotFound         = errors.New("游戏不存在")
	ErrSessionNotFound      = errors.New("会话不存在")
	ErrLevelNotFound        = errors.New("关卡不存在")
	ErrSessionLevelNotFound = errors.New("关卡会话不存在")
	ErrNoGameLevels         = errors.New("游戏没有关卡")
	ErrForbidden            = errors.New("forbidden")
	ErrInvalidPlayTime      = errors.New("无效的游玩时间")
	ErrInsufficientBeans    = errors.New("能量豆不足")
	ErrRedeemNotFound       = errors.New("兑换码不存在")
	ErrRedeemAlreadyUsed    = errors.New("兑换码已使用")
	ErrContentSeekExists    = errors.New("内容征集已存在")
	ErrFileTooLarge         = errors.New("文件大小不能超过2MB")
	ErrInvalidFileType      = errors.New("仅支持JPEG和PNG格式")
	ErrInvalidImageRole     = errors.New("无效的图片类型")
	ErrGamePublished        = errors.New("已发布的游戏不可编辑")
	ErrGameAlreadyPublished = errors.New("游戏已经是发布状态")
	ErrGameNotPublished     = errors.New("游戏未发布")
	ErrMetaNotFound         = errors.New("内容元数据不存在")
	ErrContentItemNotFound  = errors.New("练习单元不存在")
	ErrCapacityExceeded     = errors.New("超出关卡内容上限")
	ErrItemLimitExceeded    = errors.New("每条元数据练习单元数量已达上限")
	ErrGroupNotFound        = errors.New("group not found")
	ErrNotGroupOwner        = errors.New("not group owner")
	ErrAlreadyMember        = errors.New("already a group member")
	ErrAlreadyApplied       = errors.New("already applied")
	ErrApplicationNotFound  = errors.New("application not found")
	ErrNotGroupMember       = errors.New("not a group member")
	ErrCannotLeaveOwned     = errors.New("owner cannot leave own group")
	ErrSubgroupNotFound     = errors.New("subgroup not found")
)
