package api

import "errors"

var (
	ErrSessionReplaced         = errors.New("session replaced by another device")
	ErrRateLimited             = errors.New("rate limited")
	ErrInvalidCode             = errors.New("验证码无效或已过期")
	ErrDuplicateEmail          = errors.New("该邮箱已注册")
	ErrDuplicateUsername       = errors.New("用户名已被使用")
	ErrUserNotFound            = errors.New("用户不存在")
	ErrInvalidPassword         = errors.New("密码错误")
	ErrNicknameTaken           = errors.New("昵称已被使用")
	ErrImageNotFound           = errors.New("图片不存在")
	ErrImageNotOwned           = errors.New("该图片不属于您")
	ErrGameNotFound            = errors.New("游戏不存在")
	ErrSessionNotFound         = errors.New("会话不存在")
	ErrLevelNotFound           = errors.New("关卡不存在")
	ErrSessionLevelNotFound    = errors.New("关卡会话不存在")
	ErrNoGameLevels            = errors.New("游戏没有关卡")
	ErrForbidden               = errors.New("forbidden")
	ErrInvalidPlayTime         = errors.New("无效的游玩时间")
	ErrInsufficientBeans       = errors.New("能量豆不足")
	ErrRedeemNotFound          = errors.New("兑换码不存在")
	ErrRedeemAlreadyUsed       = errors.New("兑换码已使用")
	ErrContentSeekExists       = errors.New("内容征集已存在")
	ErrFileTooLarge            = errors.New("文件大小不能超过2MB")
	ErrInvalidFileType         = errors.New("仅支持JPEG和PNG格式")
	ErrInvalidImageRole        = errors.New("无效的图片类型")
	ErrGamePublished           = errors.New("已发布的游戏不可编辑")
	ErrGameAlreadyPublished    = errors.New("游戏已经是发布状态")
	ErrGameNotPublished        = errors.New("游戏未发布")
	ErrMetaNotFound            = errors.New("内容元数据不存在")
	ErrContentItemNotFound     = errors.New("练习单元不存在")
	ErrCapacityExceeded        = errors.New("超出关卡内容上限")
	ErrItemLimitExceeded       = errors.New("每条元数据练习单元数量已达上限")
	ErrGroupNotFound           = errors.New("group not found")
	ErrNotGroupOwner           = errors.New("not group owner")
	ErrAlreadyMember           = errors.New("already a group member")
	ErrAlreadyApplied          = errors.New("already applied")
	ErrApplicationNotFound     = errors.New("application not found")
	ErrNotGroupMember          = errors.New("not a group member")
	ErrCannotLeaveOwned        = errors.New("owner cannot leave own group")
	ErrSubgroupNotFound        = errors.New("subgroup not found")
	ErrGroupIsPlaying          = errors.New("game is in progress")
	ErrGroupNotPlaying         = errors.New("no game in progress")
	ErrNoGameSet               = errors.New("no game set for group")
	ErrNoGameModeSet           = errors.New("no game mode set for group")
	ErrNotInSubgroup           = errors.New("member not in any subgroup")
	ErrNotEnoughMembers        = errors.New("至少需要2名成员才能开始竞赛")
	ErrNotEnoughSubgroups      = errors.New("至少需要2个小组才能开始小组竞赛")
	ErrUnequalSubgroups        = errors.New("每个小组的成员数量必须相等")
	ErrLastLevel               = errors.New("已是最后一关")
	ErrNotGroupMemberForAction = errors.New("非群组成员")
	ErrGroupMembersFull        = errors.New("当前群组已满员")
	ErrGroupSubgroupsFull      = errors.New("每群最多 10 个小组")
	ErrOrderNotFound           = errors.New("订单不存在")
	ErrOrderNotPending         = errors.New("订单状态异常")
	ErrInvalidProduct          = errors.New("无效的商品")
	ErrVipRequired             = errors.New("升级会员解锁此功能")
)
